apiVersion: apps/v1
kind: Deployment
metadata:
  name: heavy-deploy
  labels:
    app: heavy-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heavy-api
  template:
    metadata:
      labels:
        app: heavy-api
    spec:
      containers:
      - name: api-pod
        image: registry.cloud.okteto.net/claudiuri/heavy-api-okteto:latest
        resources:
          requests:
            cpu: 500m
            memory: 512M
        env:
        - name: PORT
          value: '8086'
        ports:
        - containerPort: 8086
          name: api-port