name: Deploy

on: 
  push:
    branches: [master]

jobs:

  oketeto_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - name: "Activate Namespace"
      uses: okteto/namespace@master
      with:
        name: claudiuri
    
    - name: "Deploy application"
      uses: okteto/apply@master
      with:
        namespace: claudiuri
        manifest: ./k8s

    - name: "Push changes"
      uses: okteto/push@master
      with:
        namespace: claudiuri
        name: heavy-deploy